<a href="https://colab.research.google.com/github/laxmiharikumar/deeplearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamental concepts of tensors using tensorflow
- Introduction to Tensors

# Introduction to Tensors

In [2]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the number of dimensions of vector
vector.ndim

1

In [7]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
#Check the number of dimensions of matrix
matrix.ndim

2

In [9]:
# Create  another matrix
another_matrix = tf.constant([[10., 7.],
                              [2., 3.],
                              [8., 9.]], dtype=tf.float16) # specify the datatype with the dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 2.,  3.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3], [4,5,6]],
                      [[7,8,9], [10,11,12]],
                      [[13,14,15], [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

*   Scalar - a single number
*   Vector - a number with direction
*   Matrix - a 2 dimensional array of numbers
*   Tensor - an n dimenaional array of numbers where n >= 0


### Create tensor with `tf.Variable`

In [13]:
# Create the same tensor with tf.Variable
changeable_tensor = tf.Variable([10, 10])
unchangeable_tensor = tf.constant([10, 10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [14]:
# Change one of the variables in changeable tensor
changeable_tensor[0] = 5
changeable_tensor

TypeError: ignored

In [15]:
# Try .assign()
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 5, 10], dtype=int32)>

In [16]:
# Try to change unchangeable tensor
unchangeable_tensor[0].assign(4)
unchangeable_tensor

AttributeError: ignored

### Create random tensors

Random tensors are tensors of some arbitrary size that contain some random numbers

In [17]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [18]:
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [19]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable when you want to shuffle your data so that learning is not impacted)
not_shuffled = tf.constant([[10,7], [3,4], [2, 5]])

tf.random.shuffle(not_shuffled)

In [ ]:
not_shuffled

### Other ways of making tensors

In [20]:
# Create a tensor of ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
# Create a tensor of zeros
tf.zeros(shape=(4,3))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Create tensors from numpy

In [23]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [24]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [25]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Get information from tensors

In [26]:
# Create a rank 4 tensor (no of tensor dimensions)
B = tf.ones(shape=(2,3,4,2))
B

<tf.Tensor: shape=(2, 3, 4, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]]], dtype=float32)>

In [27]:
# Get the 0th element
B[0]

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)>

In [28]:
B.shape

TensorShape([2, 3, 4, 2])

In [29]:
B.ndim

4

In [34]:
tf.size(B).numpy()

48

In [31]:
B.dtype

tf.float32

In [33]:
#Elements along 0th axis
B.shape[0]

2

### Indexing tensors

In [36]:
# Get the first 2 elements of each dimension
B[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [38]:
# Get the first element from each dimension from each index except for the final one
B[:1, :1, :1] # Also B[:1, :1, :1, :] works

<tf.Tensor: shape=(1, 1, 1, 2), dtype=float32, numpy=array([[[[1., 1.]]]], dtype=float32)>

In [39]:
B[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.],
         [1.]]]], dtype=float32)>

In [43]:
# Create a rank 2 tensor (ndim = 2)
rank_2_tensor = tf.constant([[10,7],
                             [13,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [13,  4]], dtype=int32)>

In [44]:

print("Shape of tensor: ", rank_2_tensor.shape)
print("Rank of tensor: ", rank_2_tensor.ndim)
print("Size of tensor: ", tf.size(rank_2_tensor).numpy())

Shape of tensor:  (2, 2)
Rank of tensor:  2
Size of tensor:  4


In [50]:
# Get last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [51]:
# Add an extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[13],
        [ 4]]], dtype=int32)>

In [52]:
# Alternative approach
# Expand along 0th axis
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [13,  4]]], dtype=int32)>

In [53]:
# Expand along last axis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[13],
        [ 4]]], dtype=int32)>

In [54]:
# Expand along 1st axis
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[13,  4]]], dtype=int32)>

### Manipulating tensors

**Basic operations**

`+`, `-`, `*`, `/`

In [61]:
tensor_X = tf.constant([[10,7], [3,4]])
tensor_X + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [62]:
tensor_X -1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 6],
       [2, 3]], dtype=int32)>

In [63]:
# We can use the tensorflow built in function also
tf.multiply(tensor_X,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

In [65]:
A = tf.constant([[10,7],
                [3,4]])
tf.matmul(A, A)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [66]:
# Python matmul operator is @
A @ A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>